name: Testing application

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Test application
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Run fmt
        run: go fmt

      - name: Run tests
        run: go test -v
        env:
          DEBUG: 1
